import type {
  User,
  Project,
  Task,
  FileEntity,
  Notification,
  TimelineEvent,
  ProjectTemplate,
  WikiDocument,
  Announcement,
  SubtitleConflict,
} from "@/types";

// ========== Mock Users ==========

export const mockCurrentUser: User = {
  id: "u1",
  username: "小明",
  qq: "123456789",
  role: "supervisor",
  status: "active",
  createdAt: "2024-01-15T08:00:00Z",
};

export const mockUsers: User[] = [
  mockCurrentUser,
  { id: "u2", username: "小红", qq: "987654321", role: "member", status: "active", createdAt: "2024-02-01T10:00:00Z" },
  { id: "u3", username: "小刚", qq: "111222333", role: "member", status: "active", createdAt: "2024-03-10T14:00:00Z" },
  { id: "u4", username: "小丽", qq: "444555666", role: "group_admin", status: "active", createdAt: "2024-01-01T00:00:00Z" },
  { id: "u5", username: "小华", qq: "777888999", role: "member", status: "active", createdAt: "2024-04-20T09:00:00Z" },
];

// ========== Mock Projects ==========

export const mockProjects: Project[] = [
  {
    id: "p1",
    name: "夏日重现",
    type: "anime",
    status: "active",
    season: 1,
    episodes: 12,
    tags: ["番剧", "科幻", "悬疑"],
    supervisorId: "u1",
    supervisor: mockCurrentUser,
    members: [
      { user: mockCurrentUser, role: "supervisor", joinedAt: "2024-01-15T08:00:00Z" },
      { user: mockUsers[1], role: "translation", joinedAt: "2024-01-16T10:00:00Z" },
      { user: mockUsers[2], role: "timing", joinedAt: "2024-01-17T12:00:00Z" },
      { user: mockUsers[4], role: "encoding", joinedAt: "2024-01-18T09:00:00Z" },
    ],
    progress: 45,
    createdAt: "2024-01-15T08:00:00Z",
    updatedAt: "2024-06-20T15:30:00Z",
  },
  {
    id: "p2",
    name: "进击的巨人 最终季",
    type: "anime",
    status: "active",
    season: 4,
    episodes: 12,
    tags: ["番剧", "动作", "完结"],
    supervisorId: "u1",
    supervisor: mockCurrentUser,
    members: [
      { user: mockCurrentUser, role: "supervisor", joinedAt: "2024-03-01T08:00:00Z" },
      { user: mockUsers[1], role: "post_production", joinedAt: "2024-03-02T10:00:00Z" },
    ],
    progress: 70,
    createdAt: "2024-03-01T08:00:00Z",
    updatedAt: "2024-06-19T11:20:00Z",
  },
  {
    id: "p3",
    name: "千与千寻",
    type: "movie",
    status: "completed",
    season: 1,
    episodes: 1,
    tags: ["电影", "吉卜力", "经典"],
    supervisorId: "u4",
    supervisor: mockUsers[3],
    members: [
      { user: mockUsers[3], role: "supervisor", joinedAt: "2024-02-01T00:00:00Z" },
      { user: mockUsers[1], role: "translation", joinedAt: "2024-02-02T10:00:00Z" },
    ],
    progress: 100,
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-05-01T18:00:00Z",
  },
];

// ========== Mock Tasks ==========

export const mockTasks: Task[] = [
  {
    id: "t1",
    name: "夏日重现 第3集 - 翻译",
    projectId: "p1",
    project: mockProjects[0],
    role: "translation",
    status: "in_progress",
    assigneeId: "u2",
    assignee: mockUsers[1],
    deadline: "2024-06-25T23:59:59Z",
    dependencies: [],
    createdAt: "2024-06-15T08:00:00Z",
    updatedAt: "2024-06-20T10:00:00Z",
    fileCount: 2,
  },
  {
    id: "t2",
    name: "夏日重现 第4集 - 片源",
    projectId: "p1",
    project: mockProjects[0],
    role: "source",
    status: "submitted",
    assigneeId: "u5",
    assignee: mockUsers[4],
    deadline: "2024-06-22T23:59:59Z",
    dependencies: [],
    createdAt: "2024-06-18T09:00:00Z",
    updatedAt: "2024-06-20T14:00:00Z",
    fileCount: 1,
  },
  {
    id: "t3",
    name: "夏日重现 第2集 - 时轴",
    projectId: "p1",
    project: mockProjects[0],
    role: "timing",
    status: "overdue",
    assigneeId: "u3",
    assignee: mockUsers[2],
    deadline: "2024-06-18T23:59:59Z",
    dependencies: [],
    createdAt: "2024-06-10T08:00:00Z",
    updatedAt: "2024-06-19T16:00:00Z",
    fileCount: 1,
  },
  {
    id: "t4",
    name: "进击的巨人 第8集 - 压制",
    projectId: "p2",
    project: mockProjects[1],
    role: "encoding",
    status: "review_approved",
    assigneeId: "u5",
    assignee: mockUsers[4],
    deadline: "2024-06-28T23:59:59Z",
    dependencies: [],
    createdAt: "2024-06-12T10:00:00Z",
    updatedAt: "2024-06-19T11:20:00Z",
    fileCount: 3,
  },
  {
    id: "t5",
    name: "进击的巨人 第9集 - 后期",
    projectId: "p2",
    project: mockProjects[1],
    role: "post_production",
    status: "assigned",
    assigneeId: "u2",
    assignee: mockUsers[1],
    deadline: "2024-06-30T23:59:59Z",
    dependencies: [],
    createdAt: "2024-06-20T08:00:00Z",
    updatedAt: "2024-06-20T08:00:00Z",
    fileCount: 0,
  },
  {
    id: "t6",
    name: "夏日重现 第5集 - 审核",
    projectId: "p1",
    project: mockProjects[0],
    role: "supervisor",
    status: "submitted",
    assigneeId: "u1",
    assignee: mockCurrentUser,
    deadline: "2024-06-24T23:59:59Z",
    dependencies: [],
    createdAt: "2024-06-19T15:00:00Z",
    updatedAt: "2024-06-20T09:00:00Z",
    fileCount: 2,
  },
];

// ========== Mock Files ==========

export const mockFiles: FileEntity[] = [
  {
    id: "f1",
    name: "夏日重现_03_1080p.mkv",
    type: "video",
    projectId: "p1",
    taskId: "t1",
    uploader: mockUsers[1],
    size: 567000000,
    storageType: "s3",
    isSensitive: false,
    tags: ["片源"],
    versionCount: 3,
    createdAt: "2024-06-15T10:00:00Z",
    updatedAt: "2024-06-20T12:00:00Z",
  },
  {
    id: "f2",
    name: "夏日重现_03_翻译稿.ass",
    type: "subtitle",
    projectId: "p1",
    taskId: "t1",
    uploader: mockUsers[1],
    size: 45000,
    storageType: "local",
    isSensitive: false,
    tags: ["翻译"],
    versionCount: 2,
    createdAt: "2024-06-18T14:00:00Z",
    updatedAt: "2024-06-20T10:00:00Z",
  },
  {
    id: "f3",
    name: "夏日重现_字体包.zip",
    type: "font",
    projectId: "p1",
    uploader: mockCurrentUser,
    size: 12000000,
    storageType: "s3",
    isSensitive: false,
    tags: ["字体"],
    versionCount: 1,
    createdAt: "2024-06-10T08:00:00Z",
    updatedAt: "2024-06-10T08:00:00Z",
  },
  {
    id: "f4",
    name: "进击的巨人_08_成品.mp4",
    type: "video",
    projectId: "p2",
    taskId: "t4",
    uploader: mockUsers[4],
    size: 890000000,
    storageType: "s3",
    isSensitive: true,
    tags: ["成品", "敏感"],
    versionCount: 2,
    createdAt: "2024-06-18T16:00:00Z",
    updatedAt: "2024-06-19T11:20:00Z",
  },
  {
    id: "f5",
    name: "网盘发布链接",
    type: "other",
    projectId: "p1",
    uploader: mockCurrentUser,
    size: 0,
    storageType: "local",
    isSensitive: false,
    tags: ["发布"],
    versionCount: 1,
    createdAt: "2024-06-20T09:00:00Z",
    updatedAt: "2024-06-20T09:00:00Z",
  },
];

// ========== Mock Notifications ==========

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    type: "task",
    title: "新任务指派",
    content: "你被指派了「夏日重现 第5集 - 审核」任务",
    isRead: false,
    channels: ["in_site"],
    relatedId: "t6",
    relatedType: "task",
    createdAt: "2024-06-20T09:00:00Z",
  },
  {
    id: "n2",
    type: "review",
    title: "审核请求",
    content: "「夏日重现 第4集 - 片源」已提交，等待审核",
    isRead: false,
    channels: ["in_site", "email"],
    relatedId: "t2",
    relatedType: "task",
    createdAt: "2024-06-20T14:00:00Z",
  },
  {
    id: "n3",
    type: "file",
    title: "新文件上传",
    content: "小红上传了「夏日重现_03_翻译稿.ass」",
    isRead: true,
    channels: ["in_site"],
    relatedId: "f2",
    relatedType: "file",
    createdAt: "2024-06-20T10:00:00Z",
  },
  {
    id: "n4",
    type: "mention",
    title: "评论提及",
    content: "小刚在「夏日重现 第3集 - 翻译」中@了你",
    isRead: false,
    channels: ["in_site"],
    relatedId: "t1",
    relatedType: "task",
    createdAt: "2024-06-19T16:30:00Z",
  },
  {
    id: "n5",
    type: "system",
    title: "系统维护通知",
    content: "系统将于本周六凌晨2点进行维护升级",
    isRead: true,
    channels: ["in_site"],
    createdAt: "2024-06-18T08:00:00Z",
  },
];

// ========== Mock Timeline Events ==========

export const mockTimelineEvents: TimelineEvent[] = [
  {
    id: "e1",
    type: "task_status",
    projectId: "p1",
    projectName: "夏日重现",
    description: "夏日重现 第3集 - 翻译 已提交审核",
    user: mockUsers[1],
    createdAt: "2024-06-20T14:00:00Z",
  },
  {
    id: "e2",
    type: "file_upload",
    projectId: "p1",
    projectName: "夏日重现",
    description: "小红上传了 夏日重现_03_翻译稿.ass",
    user: mockUsers[1],
    createdAt: "2024-06-20T10:00:00Z",
  },
  {
    id: "e3",
    type: "review",
    projectId: "p2",
    projectName: "进击的巨人 最终季",
    description: "进击的巨人 第8集 - 压制 审核已通过",
    user: mockCurrentUser,
    createdAt: "2024-06-19T11:20:00Z",
  },
  {
    id: "e4",
    type: "member_join",
    projectId: "p1",
    projectName: "夏日重现",
    description: "小华 加入了 夏日重现 项目",
    user: mockUsers[4],
    createdAt: "2024-06-18T09:00:00Z",
  },
  {
    id: "e5",
    type: "system",
    description: "系统将于本周六凌晨2点进行维护",
    createdAt: "2024-06-18T08:00:00Z",
  },
  {
    id: "e6",
    type: "task_status",
    projectId: "p1",
    projectName: "夏日重现",
    description: "夏日重现 第2集 - 时轴 已超期",
    user: mockUsers[2],
    createdAt: "2024-06-18T00:00:00Z",
  },
];

// ========== Mock Templates ==========

export const mockTemplates: ProjectTemplate[] = [
  {
    id: "tmpl1",
    name: "标准番剧模板",
    type: "anime",
    description: "适用于常规季度番剧的标准工作流模板",
    roles: [
      { role: "source", enabled: true, slotCount: 1, assignmentStrategy: "manual" },
      { role: "timing", enabled: true, slotCount: 1, assignmentStrategy: "manual" },
      { role: "translation", enabled: true, slotCount: 3, assignmentStrategy: "open_claim", maxSegmentLength: 300 },
      { role: "post_production", enabled: true, slotCount: 1, assignmentStrategy: "manual" },
      { role: "encoding", enabled: true, slotCount: 1, assignmentStrategy: "manual" },
      { role: "release", enabled: true, slotCount: 1, assignmentStrategy: "manual" },
    ],
    uploadPolicy: { allowedTypes: {} as any },
    notificationPolicy: { events: {} },
    assPolicy: { mergeRule: "default", dedupThreshold: 0.1 },
    productConfig: {
      resolution: "1920x1080",
      bitrate: "8000k",
      encoder: "x264",
      containerFormat: "mkv",
      namingRule: "{title}_{ep}_{quality}",
    },
    deliveryChecklist: [
      { id: "d1", name: "成品视频", role: "encoding", required: true },
      { id: "d2", name: "外挂字幕", role: "translation", required: true },
      { id: "d3", name: "字体包", role: "post_production", required: true },
      { id: "d4", name: "封面图", role: "post_production", required: false },
    ],
    useCount: 12,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-06-01T10:00:00Z",
  },
  {
    id: "tmpl2",
    name: "电影模板",
    type: "movie",
    description: "适用于单集电影的完整工作流模板",
    roles: [
      { role: "source", enabled: true, slotCount: 1, assignmentStrategy: "manual" },
      { role: "timing", enabled: true, slotCount: 1, assignmentStrategy: "manual" },
      { role: "translation", enabled: true, slotCount: 2, assignmentStrategy: "open_claim", maxSegmentLength: 600 },
      { role: "post_production", enabled: true, slotCount: 1, assignmentStrategy: "manual" },
      { role: "encoding", enabled: true, slotCount: 1, assignmentStrategy: "manual" },
      { role: "release", enabled: true, slotCount: 1, assignmentStrategy: "manual" },
    ],
    uploadPolicy: { allowedTypes: {} as any },
    notificationPolicy: { events: {} },
    assPolicy: { mergeRule: "default", dedupThreshold: 0.1 },
    productConfig: {
      resolution: "1920x1080",
      bitrate: "12000k",
      encoder: "x264",
      containerFormat: "mkv",
      namingRule: "{title}_{quality}",
    },
    deliveryChecklist: [
      { id: "d1", name: "成品视频", role: "encoding", required: true },
      { id: "d2", name: "外挂字幕", role: "translation", required: true },
      { id: "d3", name: "字体包", role: "post_production", required: true },
    ],
    useCount: 5,
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-05-15T14:00:00Z",
  },
];

// ========== Mock Wiki ==========

export const mockWiki: WikiDocument = {
  id: "w1",
  projectId: "p1",
  title: "夏日重现 - 项目Wiki",
  blocks: [
    {
      id: "b1",
      type: "markdown",
      content: "# 项目说明\n\n本项目为《夏日重现》中文字幕制作项目。\n\n## 制作规范\n\n- 分辨率：1920x1080\n- 字体：思源黑体 Medium\n- 字号：主字幕 24px，注释 18px\n",
    },
    {
      id: "b2",
      type: "table",
      content: "",
      data: {
        headers: ["角色名", "译名", "备注"],
        rows: [
          ["網代慎平", "网代慎平", "男主角"],
          ["小舟潮", "小舟潮", "女主角"],
          ["小舟澪", "小舟澪", "潮的妹妹"],
          ["凸村哲", "凸村哲", "刑警"],
        ],
      },
    },
  ],
  status: "approved",
  updatedBy: mockCurrentUser,
  updatedAt: "2024-06-19T16:00:00Z",
};

// ========== Mock Announcements ==========

export const mockAnnouncements: Announcement[] = [
  {
    id: "a1",
    type: "global",
    title: "系统维护通知",
    content: "系统将于本周六凌晨2点进行维护升级，预计持续2小时。请提前保存您的工作。",
    createdBy: mockUsers[3],
    createdAt: "2024-06-18T08:00:00Z",
  },
  {
    id: "a2",
    type: "project",
    projectId: "p1",
    title: "夏日重现项目进度说明",
    content: "目前第1-2集已完成，第3集翻译进行中，预计本周完成全部12集。",
    createdBy: mockCurrentUser,
    createdAt: "2024-06-19T10:00:00Z",
  },
];

// ========== Mock Conflicts ==========

export const mockConflicts: SubtitleConflict[] = [
  {
    id: "c1",
    mergeJobId: "mj1",
    startTime: 125.5,
    endTime: 128.3,
    conflictType: "text_conflict",
    translations: [
      { translatorId: "u2", translatorName: "小红", text: "这不可能...", style: "Default" },
      { translatorId: "u3", translatorName: "小刚", text: "怎么会这样...", style: "Default" },
    ],
    resolution: { status: "pending" },
  },
  {
    id: "c2",
    mergeJobId: "mj1",
    startTime: 342.0,
    endTime: 345.8,
    conflictType: "exact_duplicate",
    translations: [
      { translatorId: "u2", translatorName: "小红", text: "谢谢你", style: "Default" },
      { translatorId: "u3", translatorName: "小刚", text: "谢谢你", style: "Default" },
    ],
    resolution: { status: "pending" },
  },
  {
    id: "c3",
    mergeJobId: "mj1",
    startTime: 567.2,
    endTime: 570.0,
    conflictType: "overlap",
    translations: [
      { translatorId: "u2", translatorName: "小红", text: "明天见", style: "Default" },
      { translatorId: "u3", translatorName: "小刚", text: "再见", style: "Default" },
    ],
    resolution: { status: "pending" },
  },
];
